### ISSUE TITLE
Expand validation to check fields other than Schedule State

### ISSUE THREAD

**Issue by migarjo** [github/rally#148]
**Is your feature request related to a problem? Please describe.**
This integration is currently hard-coded to validate only against the Schedule State of a Rally artifact. There are other use-cases that require validation of other fields in Rally (like State). This is particularly true of Test Cases, which do not have a Schedule State attribute

**Describe the solution you'd like**
Rather than only checking against the Schedule State attribute, this integration should allow for configuration to check any rally attribute available via the API. Since some attributes are specific to certain artifact types (i.e. Tasks, Defects, Test Cases), the configuration should be able to apply different logic to different artifacts

**Comment by scottkell012** [comment]
> **Is your feature request related to a problem? Please describe.**
> This integration is currently hard-coded to validate only against the Schedule State of a Rally artifact. There are other use-cases that require validation of other fields in Rally (like State). This is particularly true of Test Cases, which do not have a Schedule State attribute
> 
> **Describe the solution you'd like**
> Rather than only checking against the Schedule State attribute, this integration should allow for configuration to check any rally attribute available via the API. Since some attributes are specific to certain artifact types (i.e. Tasks, Defects, Test Cases), the configuration should be able to apply different logic to different artifacts

BITCOIN MINING INVESTMENT WINDOWS ARE NOW OPEN. THE OFFICIAL INVESTMENT PLANS ARE:

Payout in 7 hours


💸Invest $50 earn $500

💸Invest $100 earn $1000

💸Invest $200 earn $1500

💸Invest $300 earn $2000

💸Invest $400 earn $4000

💸Invest $500 earn $5000

💸Invest $1000 earn $10000

💸Invest $2000 earn $20000

💸Invest $3000 earn $30000 

💸Invest $4000 earn $40000 

💸Invest $5000 earn $50000

💸Invest $6000 earn $60000

No withdrawal Fee's
No hidden Fee's

PROMO PACKAGE
 👇👇👇👇👇👇👇
💎INVEST 200$ GET 2300$
💎INVEST 300$ GET 3450$
💎INVEST 400$ GET 4600$

    GOLD PACKAGE
     👇👇👇👇👇👇
💎INVEST $500 GET $5300
💎INVEST $600 GET $6300
💎INVEST $700 GET $7400
💎INVEST $800 GET $8500

FIRST 10 PEOPLE TO INVEST 
👇👇👇👇👇👇

$100 GET $2,500
$200 GET $3,600
$300 GET $4,500
$400 GET $6,500
$500 GET $7,500
$600 GET $8,500
$700 GET $9,500

HURRY WHILE PROMO 

ONGOING

Contact me now to start up your investment plan 👇
👇👇👇👇

WhatsApp +12134017827
Email   scottkell012@gmail.com to get started now!!!
