### ISSUE TITLE
Feature: Run checks on push event.

### ISSUE THREAD

**Issue by rrotaru** [github/rally#164]
**Describe the solution you'd like**
I'd like to be able to run the check suite on all commits or on commits within specific branches (without an associated pull request).

**Additional context**
Currently, the check suite only runs on pull-request payload events. The previous webhook integration for Rally supported a per-commit validation of user story IDs (this would only work if the `rally.yml` was configured to check the commit message title or body).

**Comment by primetheus** [comment]
@rrotaru this isn't really something we can implement. GitHub Apps work based on pull requests and issues. We could trigger on the `push` event, but there would be no place to report anything without having a pull request. Ultimately the app would run, but would not be able to link anything in Rally (no PR) or provide feedback to the user (again, no PR). Ideally you should have a pull request drafted when you create the new branch, and then new pushes to that branch would be validated within that pull request. If you want to check commit messages as part of a pull request you simply set the `rally.yml` to validate commit messages. The title and body give additional ways to validate, but commit messages that are part of a PR can still be checked: 

Config: https://github.com/github/rally/blob/main/rally.yml#L12
Code: https://github.com/github/rally/blob/main/lib/RallyValidate.js#L376-L401

**Comment by rrotaru** [comment]
Makes sense. Closing this issue, thanks for the reply @primetheus!
