### ISSUE TITLE
Comment on pull request references invalid Probot API context function

### ISSUE THREAD

**Issue by rrotaru** [github/rally#180]
From:
https://github.com/github/rally/blob/fd9770d6ba947405c1e9a2d47ace4f634fa177e3/lib/RallyValidate.js#L411

I get the following error when running a check with `commentOnPull: true` in the config YML:
```
14:33:23.105Z ERROR event: context.artifact is not a function (id=ad3a2180-2361-11eb-9aed-b7c419366b46)
  TypeError: context.artifact is not a function
      at RallyValidate.commentOnPull (/tech/appl/default/rally/lib/RallyValidate.js:412:28)
      at RallyValidate.handlePullRequest (/tech/appl/default/rally/lib/RallyValidate.js:184:18)
  --
  event: {
    "event": "pull_request.edited",
    "id": "ad3a2180-2361-11eb-9aed-b7c419366b46",
    "installation": 4,
    "repository": "<org>/<repo>"
  }
```

[Probot documentation](https://probot.github.io/api/latest/classes/context.html) does not list this as a valid function for the `context` object, and Git history shows that it may have been changed from `context.issue` as part of a search-and-replace [commit update](https://github.com/github/rally/commit/2bf1ecbc249b19ad99548000380e5150646879e8).

I _believe_ the correct fix would be to change that line to:
```javascript
const params = context.pullRequest({ body: message }) 
```

based on https://probot.github.io/api/latest/classes/context.html#pullrequest but I have not had time to validate that change against all of the payload events.

**Comment by nab-emre-inanli** [comment]
Could we avoid this, by turning the feature off? commentOnPull: false
