### ISSUE TITLE
Receiving octokit deprecation warning during start

### ISSUE THREAD

**Issue by recaph** [github/rally#210]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

**Describe the bug**
Receiving the following warning in the logs.
Deprecation: [@octokit/rest] Setting the "new Octokit({ auth })" option to an object without also setting the "authStrategy" option is deprecated and will be removed in v17. See (https://octokit.github.io/rest.js/#authentication)
    at authenticationPlugin (C:\Rally\node_modules\@octokit\rest\plugins\authentication\index.js:58:5)
    at C:\Rally\node_modules\@octokit\rest\lib\constructor.js:26:37
    at Array.forEach (<anonymous>)

**To Reproduce**
npm start

**Expected behavior**
No warning.

**Screenshots**

**Additional context**

**Comment by primetheus** [comment]
This will be addressed with #218
