### ISSUE TITLE
Reg-ex issue with "S3"

### ISSUE THREAD

**Issue by nab-emre-inanli** [github/rally#224]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

**Describe the bug**
Having a PR title such as "USXXXX: fix S3 bucket"
Results in "S3" getting identified as a Rally User Story.

**To Reproduce**
1. Create a new PR with the title "USXXXX: fix S3 bucket"
2. See the integration result

**Expected behavior**
Regex to ignore "S3"

**Screenshots**
Please see the screenshot.

**Additional context**
We have a basic config file, checks the PR titles.

**Comment by primetheus** [comment]
@nab-emre-inanli it looks like this is due to it being a valid Rally artifact type. https://github.com/github/rally/blob/main/lib/RallyValidate.js#L824 is where it's defined, and it could exist in RallyDev as `S3`... can you try commenting that out and see if it solves the issue for you?

**Comment by nab-emre-inanli** [comment]
@primetheus, thank you very much for the explanation.
