### ISSUE TITLE
missing brackets?

### ISSUE THREAD

**Issue by zkoppert** [github/rally#248]
Not sure if it has a significant impact, but can someone help me understand if this is causing any issue? At the following line there is an inconsistent use of square brackets. https://github.com/github/rally/blob/fe9c7d529dee708de5427070a2c3814fc3260408/lib/RallyValidate.js#L737

**Comment by Chocrates** [comment]
I don't know why it was done, but it is used on this line https://github.com/github/rally/blob/fe9c7d529dee708de5427070a2c3814fc3260408/lib/RallyValidate.js#L744

`[].concat('string')` and `[].concat(['string'])`  both result in `['string']` so it should be fine to turn it in to an array if we want.
