### ISSUE TITLE
Initial pending check fails with dynamic checks name

### ISSUE THREAD

**Issue by primetheus** [github/rally#87]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

**Describe the bug**
Dynamically setting the checks name leaves it null for the initial check

```
22:14:27.686Z ERROR event: Empty value for parameter 'name': undefined (id=3e5d1600-dce9-11ea-82b8-b135190c5ae6)
  HttpError: Empty value for parameter 'name': undefined
      at /opt/rally/node_modules/@octokit/rest/plugins/validate/validate.js:74:15
      at Array.forEach (<anonymous>)
      at /opt/rally/node_modules/@octokit/rest/plugins/validate/validate.js:42:12
      at Array.forEach (<anonymous>)
      at validate (/opt/rally/node_modules/@octokit/rest/plugins/validate/validate.js:15:23)
      at async Job.doExecute (/opt/rally/node_modules/bottleneck/light.js:405:18)
  --
  event: {
    "event": "pull_request.edited",
    "id": "3e5d1600-dce9-11ea-82b8-b135190c5ae6",
    "installation": 6,
    "repository": "GitHub-Demo/probot-rally"
  }
22:14:27.688Z ERROR probot: Empty value for parameter 'name': undefined
  HttpError: Empty value for parameter 'name': undefined
      at /opt/rally/node_modules/@octokit/rest/plugins/validate/validate.js:74:15
      at Array.forEach (<anonymous>)
      at /opt/rally/node_modules/@octokit/rest/plugins/validate/validate.js:42:12
      at Array.forEach (<anonymous>)
      at validate (/opt/rally/node_modules/@octokit/rest/plugins/validate/validate.js:15:23)
      at async Job.doExecute (/opt/rally/node_modules/bottleneck/light.js:405:18)
```

**To Reproduce**
1. Create a `.github/rally.yml` config file with a specific `checksName: <name>` set
2. Open a new pull request
3. Watch the logs

**Expected behavior**
A check should be created with the name that is defined in the `.github/rally.yml`

**Comment by primetheus** [comment]
This seems to have been a local environment issue... cannot reproduce after cleaning the env and starting over

**Comment by nab-emre-inanli** [comment]
Hi @primetheus, 

I can reproduce this issue, first time install on the Github org. 
My org has both repos configured "org-name/.github/rally.yml" and 
"org-name/rally-github-config/.github/rally.yml"

ERROR probot: Empty value for parameter 'name': undefined
HttpError: Empty value for parameter 'name': undefined

.env file does not have anything missing, exact copy of yours. 

However, after creating a .github/rally.yml in my repository, issue goes away. 

Regards,
Emre
