### ISSUE TITLE
License not reported by GitHub UI

### ISSUE THREAD

**Issue by zkoppert** [github/rally#91]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

**Describe the bug**
The GitHub UI does not report that the project has a license.

**To Reproduce**
1. Go to github.com/github
1. Search for rally
1. Observe that no license is reported in the metadata below the repo
<img width="670" alt="Screen Shot 2020-08-13 at 5 02 50 PM" src="https://user-images.githubusercontent.com/6935431/90198543-d52be000-dd86-11ea-9c5e-783744491637.png">

also

1. Go to github.com/github/rally
1. Observe that in the right side panel no license is reported
<img width="249" alt="Screen Shot 2020-08-13 at 5 01 34 PM" src="https://user-images.githubusercontent.com/6935431/90198505-bc232f00-dd86-11ea-9175-dcc3a84e36c8.png">

**Expected behavior**
The GitHub UI should detect and report the license and its type
<img width="253" alt="Screen Shot 2020-08-13 at 4 57 48 PM" src="https://user-images.githubusercontent.com/6935431/90198499-b75e7b00-dd86-11ea-8b25-277026a24019.png">
<img width="667" alt="Screen Shot 2020-08-13 at 5 03 20 PM" src="https://user-images.githubusercontent.com/6935431/90198567-e83eb000-dd86-11ea-82f5-422344247fd2.png">

**Screenshots**
see inline above

**Additional context**
It was moved from the repo root directory to the `.github/` at a9825af65f4eef37d917764e7d41e6b9480c8d53  but I'm not sure for what reason.

**Comment by primetheus** [comment]
>It was moved from the repo root directory to the .github/ at a9825af but I'm not sure for what reason.

@zkoppert just for the cleanness of having the root directory being for code.

**Comment by primetheus** [comment]
I didn't realize that nesting it there would affect the UI... seems that's one of the few docs that _needs_ to be in the root
